#pragma once
#include "CoreMinimal.h"
#include "EEndBattleCountLogType.generated.h"

UENUM()
enum class EEndBattleCountLogType : uint8 {
    NormalAttackInvoke,
    NormalAttackHitSuccess,
    NormalAttackPerHitSuccess,
    NormalAttackHitFailure,
    NormalAttackPerHitFailure,
    NormalAttackEnd,
    WeaponAbilityInvoke,
    WeaponAbilityHitSuccess,
    WeaponAbilityPerHitSuccess,
    WeaponAbilityHitFailure,
    WeaponAbilityPerHitFailure,
    WeaponAbilityEnd,
    MagicInvoke,
    MagicHitSuccess,
    MagicPerHitSuccess,
    MagicHitFailure,
    MagicPerHitFailure,
    MagicEnd,
    LimitInvoke,
    LimitHitSuccess,
    LimitPerHitSuccess,
    LimitHitFailure,
    LimitPerHitFailure,
    LimitEnd,
    PerHitSuccessAttribute,
    ItemUse,
    SummonStayBegin,
    SummonCutSceneAbilityBegin,
    SummonCutSceneAbilityEnd,
    Burst,
    BurstEnd,
    IsSyncAction,
    SyncActionState,
    SpecialStatusChangeState,
    ExclusiveCondition,
    ControledChara,
    LeaderChange,
    PartyCommand,
    HPPercent,
    LimitPercent,
    ATBValue,
    ATBUsedValue,
    IsDead,
    BattleBegin,
    UCPCBattle,
    KilledEnemy,
    OwnKilledEnemy,
    AlivePCParty,
    UnrunnableTalkState,
    RunnedSpecificTalkState,
    SpecificTalkStateElapseTime,
    SpecificTalkStateIntervalTime,
    SpecificTalkStatePlayedCount,
    IsStoryFlag,
    BattleSceneTime,
    MAX,
};

