#pragma once
#include "CoreMinimal.h"
#include "EEndLoadLevelPriority.generated.h"

UENUM()
enum class EEndLoadLevelPriority : uint8 {
    STREAM_LEVEL_BACK_GROUND = 0x40,
    STREAM_LEVEL_DEFAULT_PRIORITY = 0x80,
    STREAM_LEVEL_LEVELSEQUENCELOADER_ANIMATION_PRIORITY = 0xA0,
    STREAM_LEVEL_CHARA_POP_LOAD_PRIORITY = 0xA0,
    STREAM_LEVEL_CHARA_POP_UNLOAD_PRIORITY,
    STREAM_LEVEL_ENVSET_PRIORITY = 0xAA,
    STREAM_LEVEL_ABILITY_PRIORITY = 0xB4,
    STREAM_LEVEL_MENU_PRIORITY = 0xBE,
    STREAM_LEVEL_LOCATION_ENTRY_PRIORITY = 0xC3,
    STREAM_LEVEL_FIRST_CINEMA_PRIORITY = 0xC8,
    STREAM_LEVEL_PLANER_CINEMA_PRIORITY = 0xD2,
    STREAM_LEVEL_PARTY_CHARACTER_PRIORITY = 0xE6,
    STREAM_LEVEL_SECONDRY_CINEMA_PRIORITY = 0xFE,
    STREAM_LEVEL_UNLOAD,
    STREAM_LEVEL_MAX UMETA(Hidden),
};

