#pragma once
#include "CoreMinimal.h"
#include "EEndLoadLevelPriority.generated.h"

UENUM(BlueprintType)
enum class EEndLoadLevelPriority : uint8 {
    STREAM_LEVEL_BACK_GROUND,
    STREAM_LEVEL_DEFAULT_PRIORITY,
    STREAM_LEVEL_LEVELSEQUENCELOADER_ANIMATION_PRIORITY,
    STREAM_LEVEL_CHARA_POP_LOAD_PRIORITY,
    STREAM_LEVEL_CHARA_POP_UNLOAD_PRIORITY,
    STREAM_LEVEL_ENVSET_PRIORITY,
    STREAM_LEVEL_ABILITY_PRIORITY,
    STREAM_LEVEL_MENU_PRIORITY,
    STREAM_LEVEL_LOCATION_ENTRY_PRIORITY,
    STREAM_LEVEL_FIRST_CINEMA_PRIORITY,
    STREAM_LEVEL_PLANER_CINEMA_PRIORITY,
    STREAM_LEVEL_PARTY_CHARACTER_PRIORITY,
    STREAM_LEVEL_SECONDRY_CINEMA_PRIORITY,
    STREAM_LEVEL_UNLOAD,
    STREAM_LEVEL_MAX UMETA(Hidden),
};

