#pragma once
#include "CoreMinimal.h"
#include "EEndBattleSpecialStatusChangeType.generated.h"

UENUM(BlueprintType)
enum class EEndBattleSpecialStatusChangeType : uint8 {
    None,
    Barrier,
    SearchLaser,
    StunBoss,
    AIHands,
    RocketPunch,
    CatchWithChain,
    CanNotAbility,
    CatchedByChain,
    SyncAction,
    Doping,
    StunEnemy,
    LaunchByPhysics,
    CatchWithChainDamageSource,
    ReactionDamageSource,
    DamageInvalid,
    LockOn,
    LockedOn,
    LocateDamageSource,
    CatchWithHandle,
    CatchedByHandle,
    WarpStyle,
    HideStyle,
    Appear,
    HitSlowAttack,
    BarretBuff,
    ControlEnvironmentActor,
    ReplaceEnvironmentActor,
    ThrowEnvironmentActor,
    TifaBuff,
    CounterMode,
    ControlEnvironmentActorGroup,
    GhostStyle,
    BarretHPTransferBuff,
    ScreenInterference,
    AerithAssist,
    PlayTouchEffect,
    PlayTouchEffectTargetIDGroup,
    PlayTouchEffectFeet,
    PlayBlendSpaceAction,
    OverwriteSyncAction,
    Bind,
    ApparentDeath,
    IceAura,
    SoulAbsorb,
    ThrowCharacter,
    ResetThrowCharacter,
    InRangeCheckDamage,
    SephirothWarpStyle,
    CamouflageStyle,
    BPDoT,
    HPDoT,
    YuffieCalcDamageBuff,
    YuffieAttributeBuff,
    RamuhPowerUp,
    PushCollisionController,
    HateManagementOwner,
    HateManagementTarget,
    SononTargetFixedBuff,
    OneAbilityCalcDamageBuff,
    BadConditionTop = 0x64,
    ChokeBadCondition = 0x64,
    BurnBadCondition,
    FrostBadCondition,
    ShockBadCondition,
    StunBadCondition,
    StunState = 0x68,
    WeakBadCondition,
    BadConditionBottom,
    BadSignConditionTop = 0x6E,
    ChokeBadSignCondition = 0x6E,
    BurnBadSignCondition,
    FrostBadSignCondition,
    ShockBadSignCondition,
    StunBadSignCondition,
    BadSignConditionBottom,
    SummonBuffTop = 0xDC,
    SummonBuffRegene = 0xDC,
    SummonBuffMaxHpBonus = 0xDF,
    SummonBuffPhysicalAttackBonus,
    SummonBuffMagicAttackBonus,
    SummonBuffBottom,
    MAX,
};

