#pragma once
#include "CoreMinimal.h"
#include "eBodyParts.generated.h"

UENUM()
enum eBodyParts {
    kPartPelvis,
    kPartSpineBase,
    kPartSpine1,
    kPartSpine2,
    kPartSpine3,
    kPartSpine4,
    kPartNeckBase,
    kPartNeck1,
    kPartNeck2,
    kPartNeck3,
    kPartNeck4,
    kPartTailBase,
    kPartTail1,
    kPartTail2,
    kPartTail3,
    kPartTail4,
    kPartLeftArmBase,
    kPartLeftArm1,
    kPartLeftArm2,
    kPartLeftArm3,
    kPartLeftArm4,
    kPartRightArmBase,
    kPartRightArm1,
    kPartRightArm2,
    kPartRightArm3,
    kPartRightArm4,
    kPartLeftLegBase,
    kPartLeftLeg1,
    kPartLeftLeg2,
    kPartLeftLeg3,
    kPartLeftLeg4,
    kPartRightLegBase,
    kPartRightLeg1,
    kPartRightLeg2,
    kPartRightLeg3,
    kPartRightLeg4,
    kAppendage1,
    kAppendage2,
    kAppendage3,
    kAppendage4,
    kAppendage5,
    kAppendage6,
    kAppendage7,
    kAppendage8,
    kAppendage9,
    kAppendage10,
    kAppendage11,
    kAppendage12,
    kAppendage13,
    kAppendage14,
    kAppendage15,
    kAppendage16,
    kAppendage17,
    kAppendage18,
    kAppendage19,
    kInvalidPart,
    kNumPossibleParts,
};

